In [1]:
import pandas as pd
import numpy as np
import unicodedata

# Revisión de los archivos originales en la carpeta crudos
archivos_excel = [
    'DATOS/Datos crudos/Resultados de la votación 2017.xlsx',
    'DATOS/Datos crudos/Resultados de la votación 2018.xlsx',
    'DATOS/Datos crudos/Resultados de la votación 2019.xlsx',
    'DATOS/Datos crudos/Resultados de la votación 2021.xlsx',
    'DATOS/Datos crudos/Resultados de la votación 2022.xlsx',
    'DATOS/Datos crudos/Resultados de la votación 2023.xlsx',
    'DATOS/Datos crudos/Resultados de la votación 2024.xlsx',
    'DATOS/Datos crudos/Resultados de la votación 2025.xls'
]

for nombre in archivos_excel:
    temp_df = pd.read_excel(nombre)
    print(f"--- Columnas en {nombre} ---")
    print(temp_df.columns.tolist())
    print("\n")

--- Columnas en DATOS/Datos crudos/Resultados de la votación 2017.xlsx ---
['Cantidad de votos', 'Orden en la votación', 'GANADOR', 'BARRIO', 'PROYECTO', 'PRESUPUESTO ESTIMADO', 'Suma presupuesto proyectos ganadores']


--- Columnas en DATOS/Datos crudos/Resultados de la votación 2018.xlsx ---
['Unnamed: 0', 'Olivos - 5 proyectos ganadores', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']


--- Columnas en DATOS/Datos crudos/Resultados de la votación 2019.xlsx ---
['Nº DE PROYECTO EN LA BOLETA DEL BARRIO', 'Cantidad de votos obtenidos por el proyecto', 'Orden en la votación seguún cantidad de votos obtenidos', 'GANADOR', 'BARRIO', 'PROYECTO', 'PRESUPUESTO ESTIMADO', 'Observaciones', 'Suma presupuestos proyectos ganadores por barrio']


--- Columnas en DATOS/Datos crudos/Resultados de la votación 2021.xlsx ---
['Nro. Proyecto en el Barrio', 'Cantidad de votos obtenidos', 'Orden en la votación según cantidad de votos', 'GANADOR', 'Barrio', 'Proyecto', 'Descripción', 'Presupuesto Estimado', 'Observaciones', 'Suma presupuestos proyectos ganadores por barrio']

c:\Users\cerru\OneDrive\Documentos\TP FINAL DATOS\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\cerru\OneDrive\Documentos\TP FINAL DATOS\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

--- Columnas en DATOS/Datos crudos/Resultados de la votación 2022.xlsx ---
['N° Proyecto en el Barrio', 'Cantidad de votos obtenidos', 'Orden en la votación según cantidad de votos', 'GANADOR', 'Barrio', 'Proyecto', 'Descripción', 'Presupuesto Estimado', 'Observaciones', 'Suma presupuestos proyectos ganadores por barrio', 'Disponible para el barrio en 2023']


--- Columnas en DATOS/Datos crudos/Resultados de la votación 2023.xlsx ---
['N° Proy en el Barrio', 'Cantidad de votos obtenidos', 'Orden en la votación', 'GANADOR', 'Num barrio', 'Barrio', 'Proyecto', 'Descripción', 'Presupuesto Estimado', 'Observaciones', 'Disponible para el barrio en 2024']


--- Columnas en DATOS/Datos crudos/Resultados de la votación 2024.xlsx ---
['N° Proy en el Barrio', 'Cantidad de votos obtenidos', 'Orden en la votación', 'GANADOR', 'Num barrio', 'Barrio', 'Proyecto', 'Descripción', 'Presupuesto Estimado', 'Observaciones', 'Disponible para el barrio en 2025']


--- Columnas en DATOS/Datos crudos/Resultados de la votación 2025.xls ---
['N° Proy en el Barrio', 'Cantidad de votos obtenidos', 'Orden en la votación', 'Ganador', 'Barrio', 'Proyecto', 'Descripción', 'Presupuesto Estimado', 'Observaciones', 'Disponible para el barrio en 2026']

In [2]:
#El archivo de 2018 tenía los datos separados por hoja por barrio. Se recorre cada hoja, se le asigna el nombre del barrio a cada fila y luego las une en una sola tabla para analizar el año completo

archivo_2018 = 'DATOS/Datos crudos/Resultados de la votación 2018.xlsx'

hojas_dict = pd.read_excel(archivo_2018, sheet_name=None, header=1)

lista_de_tablas = []

for nombre_de_la_hoja, tabla_de_la_hoja in hojas_dict.items():
    tabla_de_la_hoja.columns = [str(c).lower().strip() for c in tabla_de_la_hoja.columns]
    
    tabla_de_la_hoja['Localidades'] = nombre_de_la_hoja
    
    lista_de_tablas.append(tabla_de_la_hoja)

df_2018_completo = pd.concat(lista_de_tablas, ignore_index=True)

print("Barrios procesados de las hojas:")
print(df_2018_completo['Localidades'].unique())

df_2018_completo.head()

Barrios procesados de las hojas:
<StringArray>
[        'Olivos', 'Villa Martelli',  'Florida Oeste',          'Munro',
     'Carapachay',  'Villa Adelina',      'La Lucila',   'Florida Este',
  'Vicente López']
Length: 9, dtype: str

,número de proyecto,descripción,votos válidos,presupuesto estimado del proyecto,observaciones,Localidades,votos
0,NaN,NaN,NaN,NaN,PP del barrio: $ 9.833.333,Olivos,NaN
1,9.0,ASOCIACIÓN VECINAL DE FOMENTO Y CULTURA NORTE ...,2753.0,7000000.0,GANADOR,Olivos,NaN
2,27.0,ESCUELAS PRIMARIA Y SECUNDARIA Nº 1: equipamiento,1590.0,2000000.0,GANADOR,Olivos,NaN
3,5.0,ESCUELA PRIMARIA Nº 2: reparaciones varias en ...,1498.0,2000000.0,excede pres. Esc. Provinciales,Olivos,NaN
4,10.0,COLEGIO VIRGEN DEL CARMEN:Cambiar cielorrasos ...,1323.0,438800.0,GANADOR,Olivos,NaN

In [3]:
#Se mapea y limpian los datos de 2018, renombrando columnas originales a nombres comunes con los otros años. 
#Además filtra la info relevante y elimina las filas vacías
dict_hojas = pd.read_excel('DATOS/Datos crudos/Resultados de la votación 2018.xlsx', sheet_name=None, header=1)

lista_final_2018 = []

for nombre_barrio, df_hoja in dict_hojas.items():
    df_hoja.columns = [str(c).lower().strip() for c in df_hoja.columns]
    
    mapeo = {
        'votos válidos': 'Votos',
        'descripción': 'Proyecto',
        'presupuesto estimado del proyecto': 'Presupuesto',
        'observaciones': 'Ganador'
    }
    
    df_hoja = df_hoja.rename(columns=mapeo)
    
    df_hoja['Barrio'] = nombre_barrio
    df_hoja['Año'] = 2018
    
    cols_interes = ['Votos', 'Localidades', 'Proyecto', 'Presupuesto', 'Ganador', 'Año']
    df_hoja = df_hoja[[c for c in cols_interes if c in df_hoja.columns]]
    
    lista_final_2018.append(df_hoja)

df_2018_final = pd.concat(lista_final_2018, ignore_index=True)

df_2018_final = df_2018_final.dropna(subset=['Votos', 'Proyecto'], how='all')

print("Todas las localidades están unificadas.")
df_2018_final.sample(10)

Todas las localidades están unificadas.

,Votos,Proyecto,Presupuesto,Ganador,Año
187,NaN,Plan de fomento de lectura en la infancia: tal...,60000.0,excede presupuesto,2018
105,333.0,RAMPAS EN EL BARRIO,3542500.0,excede presupuesto,2018
155,64.0,CESTOS PAPELEROS: Av. Maipú de Roma a Paraná,142500.0,GANADOR,2018
82,59.0,Promoción de la lectura en la primera infancia...,75000.0,excede presupuesto,2018
165,NaN,ESCUELA SECUNDARIA N° 8: reparación de techos ...,1000000.0,excede presupuesto,2018
132,122.0,CESTOS PAPELEROS EN EL BARRIO,189000.0,GANADOR,2018
50,233.0,Campaña de revaloración de la tercera edad en ...,426950.0,excede presupuesto,2018
163,NaN,"CRUZ ROJA: Escuela de Enfermería, reparación d...",1540000.0,excede presupuesto,2018
129,212.0,RAMPAS EN EL BARRIO,1397500.0,excede presupuesto,2018
83,29.0,SEÑALIZAR ESTACIONAMIENTO PARA DISCAPACITADOS ...,500500.0,excede presupuesto,2018

In [4]:
#Se procesan los años estandarizando los nombres de las columnas y chequear que todos los archivos se carguen sin errores de compatibilidad
archivos_otros_años = {
    2017: 'DATOS/Datos crudos/Resultados de la votación 2017.xlsx',
    2019: 'DATOS/Datos crudos/Resultados de la votación 2019.xlsx',
    2021: 'DATOS/Datos crudos/Resultados de la votación 2021.xlsx',
    2022: 'DATOS/Datos crudos/Resultados de la votación 2022.xlsx',
    2023: 'DATOS/Datos crudos/Resultados de la votación 2023.xlsx',
    2024: 'DATOS/Datos crudos/Resultados de la votación 2024.xlsx',
    2025: 'DATOS/Datos crudos/Resultados de la votación 2025.xls'
}

lista_dfs = []
for año, archivo in archivos_otros_años.items():
    engine = 'xlrd' if archivo.endswith('.xls') else 'openpyxl'
    
    df_temp = pd.read_excel(archivo, engine=engine)
    
    df_temp.columns = [str(c).lower().strip() for c in df_temp.columns]
    
    mapeo = {
        'cantidad de votos obtenidos': 'Votos', 
        'cantidad de votos': 'Votos', 
        'presupuesto estimado': 'Presupuesto', 
        'ganador': 'Ganador', 
        'barrio': 'Localidades', 
        'proyecto': 'Proyecto'
    }
    
    df_temp = df_temp.rename(columns=mapeo)
    df_temp['Año'] = año
    lista_dfs.append(df_temp)

c:\Users\cerru\OneDrive\Documentos\TP FINAL DATOS\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\cerru\OneDrive\Documentos\TP FINAL DATOS\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [5]:
#Carga del archivo histórico de proyectos ganadores
archivo_historico= 'DATOS/Datos crudos/Históricos Presupuesto.xlsx'

df_historico=pd.read_excel(archivo_historico)

#Se filtran sólo los años entre 2013 y 2016
df_historico=df_historico[df_historico['Año'].isin([2013,2014,2015,2016])].copy()

#Renombramos columnas
mapeo_historico={
    'Año':'Año',
    'Barrio':'Localidades',
    'Título Proyecto':'Proyecto',
    'Presupuesto invertido':'Presupuesto',
    'Cantidad de votos válidos obtenidos':'Votos'
}

df_historico=df_historico.rename(columns=mapeo_historico)

cols_a_limpiar = ['Votos', 'Presupuesto']

for col in cols_a_limpiar:
    #Convertimos a string y quitamos puntos, comas, signos de pesos y espacios
    df_historico[col] = df_historico[col].astype(str).str.replace(r'[$.]', '', regex=True).str.replace(',', '.', regex=True).str.strip()
   
    #Convertimos a numérico y luego a entero
    df_historico[col] = pd.to_numeric(df_historico[col], errors='coerce').fillna(0).astype(int)

#Se aplica la función de categorías como "Sin Clasificar" para luego sobreescribirlo 
df_historico['Categoria'] = 'Sin clasificar'

filtro_cero = (df_historico['Votos'] == 0)

# Imputamos la media de 540
df_historico.loc[filtro_cero, 'Votos'] = 540

# Nos aseguramos que el ganador sea 1
df_historico['Ganador_bin'] = 1

# Forzamos a que sea un número entero
df_historico['Ganador_bin'] = df_historico['Ganador_bin'].astype(int)

# Seleccionamos las columnas finales
columnas_finales = ['Año','Localidades','Proyecto','Categoria','Votos','Presupuesto','Ganador_bin']
df_historico_final = df_historico[columnas_finales]

# Agregamos a nuestra lista
lista_dfs.append(df_historico_final)

print("2013-2016 integrados")

2013-2016 integrados

In [6]:
# Se unifica la lista
vilo_master = pd.concat(lista_dfs + [df_2018_final], ignore_index=True)

# Colocamos la categoría como "Sin clasificar" para luego sobreescribirlo 
vilo_master['Categoria'] = 'Sin clasificar'

# Creamos la lógica para los años que SÍ tienen la columna 'Ganador'
condicion_ganador = vilo_master['Ganador'].apply(lambda x: str(x).strip().upper() in ['SI', 'GANADOR'])

# Solo aplicamos la lógica a las filas que NO son 2013-2016
mascara_otros_años = ~vilo_master['Año'].isin([2013, 2014, 2015, 2016])

vilo_master.loc[condicion_ganador & mascara_otros_años, 'Ganador_bin'] = 1
vilo_master.loc[~condicion_ganador & mascara_otros_años, 'Ganador_bin'] = 0

# Finalmente, para asegurarnos de que no quede ningún NaN, rellenamos cualquier hueco que haya quedado con 0
vilo_master['Ganador_bin'] = vilo_master['Ganador_bin'].fillna(0).astype(int)
# ---------------------------

#Guardamos el resultado final
vilo_master.to_csv('DATOS/Datos procesados/dataset_final_vilo.csv', index=False, encoding='utf-8-sig')
print("¡Todo unificado con éxito!")

¡Todo unificado con éxito!

In [7]:
#Hacemos la copia
df_limpio = vilo_master.copy()

#Unificamos columnas de votos
columnas_votos = ['cantidad de votos obtenidos por el proyecto', 'cantidad de votos obtenidos']
for col in columnas_votos:
    if col in df_limpio.columns:
        df_limpio['Votos'] = df_limpio['Votos'].fillna(df_limpio[col])

#Unificamos descripción
if 'descripción' in df_limpio.columns:
    df_limpio['proyecto'] = df_limpio['Proyecto'].fillna(df_limpio['descripción'])

#Rescatamos ganadores de observaciones
if 'observaciones' in df_limpio.columns:
    mask = df_limpio['observaciones'].str.contains('GANADOR', na=False, case=False)
    df_limpio.loc[mask, 'Ganador_bin'] = 1

# Limpiamos espacios y mayúsculas
df_limpio['Localidades'] = df_limpio['Localidades'].astype(str).str.upper().str.strip()

# Diccionario de corrección
mapeo_localidades = {
    'V. LOPEZ': 'Vicente López',
    'VTE LOPEZ': 'Vicente López',
    'VICENTE LOPEZ': 'Vicente López',
    'VICENTE LÓPEZ': 'Vicente López',
    'FLORIDA ESTE': 'Florida Este',
    'FLORIDA OESTE': 'Florida Oeste',
    'LA LUCILA': 'La Lucila',
    'MUNRO': 'Munro',
    'OLIVOS': 'Olivos',
    'CARAPACHAY': 'Carapachay',
    'VILLA ADELINA': 'Villa Adelina',
    'VILLA MARTELLI': 'Villa Martelli'
}

# Aplicamos el mapeo, si no está en el diccionario, mantiene el original
df_limpio['Localidades'] = df_limpio['Localidades'].map(mapeo_localidades).fillna(df_limpio['Localidades'])

#Selección de columnas finales
columnas_finales = [
    'Año', 
    'Localidades', 
    'Proyecto', 
    'Categoria', 
    'Votos', 
    'Presupuesto', 
    'Ganador_bin'
]

dataset_tif = df_limpio[columnas_finales].copy()

#Limpieza de filas y conversión a ENTEROS (int)
dataset_tif = dataset_tif.dropna(subset=['Proyecto', 'Localidades'])

dataset_tif['Votos'] = pd.to_numeric(dataset_tif['Votos'], errors='coerce').fillna(0).astype(int)
dataset_tif['Presupuesto'] = pd.to_numeric(dataset_tif['Presupuesto'], errors='coerce').fillna(0).astype(int)

# CORRECCIÓN DE RUTAS:
ruta_salida = 'DATOS/Datos procesados/dataset_final_vilo.csv'

dataset_tif.to_csv(ruta_salida, index=False, sep=';', encoding='utf-8-sig')

print("Dataset pulido y guardado")
print(f"Total de registros: {len(dataset_tif)}")
dataset_tif.head()

Dataset pulido y guardado
Total de registros: 1528

,Año,Localidades,Proyecto,Categoria,Votos,Presupuesto,Ganador_bin
0,2017,Villa Martelli,BOMBEROS VOLUNTARIOS DE VICENTE LÓPEZ - 25 equ...,Sin clasificar,959,978500,1
1,2017,Villa Martelli,CAMPAÑA DE CONCIENTIZACIÓN SOBRE EL BULLYING -...,Sin clasificar,506,193892,1
2,2017,Villa Martelli,FUNDACION CAMINO - Remodelación interior y fac...,Sin clasificar,487,1500000,1
3,2017,Villa Martelli,ESCUELA SECUNDARIA Nº 2 (provincial) - Reparac...,Sin clasificar,482,1200000,1
4,2017,Villa Martelli,BIBLIOTECA FROILÁN GONZÁLEZ - Compra de mobili...,Sin clasificar,446,132000,1

In [8]:
from transformers import pipeline

classifier = pipeline(
    "zero-shot-classification",
    model="joeddav/xlm-roberta-large-xnli",
    device=0 if __import__('torch').cuda.is_available() else -1
)

categorias = [
    'Salud y medicina',
    'Cultura y patrimonio histórico',
    'Educación y escuelas',
    'Seguridad y bomberos',
    'Movilidad y tránsito',
    'Medio ambiente y reciclaje',
    'Deporte y clubes deportivos',
    'Plazas y espacios públicos',
    'Construcción y reparaciones edilicias',
    'Organizaciones sociales y comunitarias'
]

BATCH = 32
titulos = dataset_tif['Proyecto'].tolist()
categorias_resultado = []

for i in range(0, len(titulos), BATCH):
    lote = titulos[i:i+BATCH]
    lote_limpio = [
        str(t) if pd.notna(t) and str(t).strip() != "" 
        else "proyecto sin descripción" 
        for t in lote
    ]
    resultados = classifier(lote_limpio, candidate_labels=categorias)
    categorias_resultado.extend([r['labels'][0] for r in resultados])
    print(f"Procesados {min(i+BATCH, len(titulos))}/{len(titulos)}")

dataset_tif['Categoria'] = categorias_resultado

dataset_tif.to_csv(
    'DATOS/Datos procesados/dataset_final_vilo.csv', 
    index=False, sep=';', encoding='utf-8-sig'
)
print("Clasificación NLP completa y guardada")
print(dataset_tif['Categoria'].value_counts())

c:\Users\cerru\OneDrive\Documentos\TP FINAL DATOS\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
c:\Users\cerru\OneDrive\Documentos\TP FINAL DATOS\.venv\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\cerru\.cache\huggingface\hub\models--joeddav--xlm-roberta-large-xnli. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Loading weights: 100%|██████████| 393/393 [00:00<00:00, 4502.08it/s]
[transformers] XLMRobertaForSequenceClassification LOAD REPORT from: joeddav/xlm-roberta-large-xnli
Key                         | Status     |  |
----------------------------+------------+--+-
roberta.pooler.dense.weight | UNEXPECTED |  |
roberta.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Procesados 32/1528
Procesados 64/1528
Procesados 96/1528
Procesados 128/1528
Procesados 160/1528
Procesados 192/1528
Procesados 224/1528
Procesados 256/1528
Procesados 288/1528
Procesados 320/1528
Procesados 352/1528
Procesados 384/1528
Procesados 416/1528
Procesados 448/1528
Procesados 480/1528
Procesados 512/1528
Procesados 544/1528
Procesados 576/1528
Procesados 608/1528
Procesados 640/1528
Procesados 672/1528
Procesados 704/1528
Procesados 736/1528
Procesados 768/1528
Procesados 800/1528
Procesados 832/1528
Procesados 864/1528
Procesados 896/1528
Procesados 928/1528
Procesados 960/1528
Procesados 992/1528
Procesados 1024/1528
Procesados 1056/1528
Procesados 1088/1528
Procesados 1120/1528
Procesados 1152/1528
Procesados 1184/1528
Procesados 1216/1528
Procesados 1248/1528
Procesados 1280/1528
Procesados 1312/1528
Procesados 1344/1528
Procesados 1376/1528
Procesados 1408/1528
Procesados 1440/1528
Procesados 1472/1528
Procesados 1504/1528
Procesados 1528/1528
Clasificación NLP completa y guardada
Categoria
Movilidad y tránsito                      388
Organizaciones sociales y comunitarias    309
Educación y escuelas                      239
Deporte y clubes deportivos               170
Plazas y espacios públicos                154
Construcción y reparaciones edilicias     113
Medio ambiente y reciclaje                 78
Salud y medicina                           43
Cultura y patrimonio histórico             26
Seguridad y bomberos                        8
Name: count, dtype: int64

In [9]:
print(dataset_tif['Categoria'].value_counts())

Categoria
Movilidad y tránsito                      388
Organizaciones sociales y comunitarias    309
Educación y escuelas                      239
Deporte y clubes deportivos               170
Plazas y espacios públicos                154
Construcción y reparaciones edilicias     113
Medio ambiente y reciclaje                 78
Salud y medicina                           43
Cultura y patrimonio histórico             26
Seguridad y bomberos                        8
Name: count, dtype: int64

In [12]:
from transformers import pipeline

classifier = pipeline(
    "zero-shot-classification",
    model="Recognai/bert-base-spanish-wwm-cased-xnli",
    device=0 if __import__('torch').cuda.is_available() else -1
)

categorias = [
    'Salud y medicina',
    'Cultura y patrimonio histórico',
    'Educación y escuelas',
    'Seguridad y bomberos',
    'Movilidad y tránsito',
    'Medio ambiente y reciclaje',
    'Deporte y clubes deportivos',
    'Plazas y espacios públicos',
    'Construcción y reparaciones edilicias',
    'Organizaciones sociales y comunitarias'
]

BATCH = 32
titulos = dataset_tif['Proyecto'].tolist()
categorias_resultado = []

for i in range(0, len(titulos), BATCH):
    lote = titulos[i:i+BATCH]
    lote_limpio = [
        str(t) if pd.notna(t) and str(t).strip() != ""
        else "proyecto sin descripción"
        for t in lote
    ]
    resultados = classifier(lote_limpio, candidate_labels=categorias)
    categorias_resultado.extend([r['labels'][0] for r in resultados])
    print(f"Procesados {min(i+BATCH, len(titulos))}/{len(titulos)}")

dataset_tif['Categoria'] = categorias_resultado

dataset_tif.to_csv(
    'DATOS/Datos procesados/dataset_final_vilo.csv',
    index=False, sep=';', encoding='utf-8-sig'
)
print("Clasificación NLP completa y guardada")
print(dataset_tif['Categoria'].value_counts())

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 5466.50it/s]

Procesados 32/1528
Procesados 64/1528
Procesados 96/1528
Procesados 128/1528
Procesados 160/1528
Procesados 192/1528
Procesados 224/1528
Procesados 256/1528
Procesados 288/1528
Procesados 320/1528
Procesados 352/1528
Procesados 384/1528
Procesados 416/1528
Procesados 448/1528
Procesados 480/1528
Procesados 512/1528
Procesados 544/1528
Procesados 576/1528
Procesados 608/1528
Procesados 640/1528
Procesados 672/1528
Procesados 704/1528
Procesados 736/1528
Procesados 768/1528
Procesados 800/1528
Procesados 832/1528
Procesados 864/1528
Procesados 896/1528
Procesados 928/1528
Procesados 960/1528
Procesados 992/1528
Procesados 1024/1528
Procesados 1056/1528
Procesados 1088/1528
Procesados 1120/1528
Procesados 1152/1528
Procesados 1184/1528
Procesados 1216/1528
Procesados 1248/1528
Procesados 1280/1528
Procesados 1312/1528
Procesados 1344/1528
Procesados 1376/1528
Procesados 1408/1528
Procesados 1440/1528
Procesados 1472/1528
Procesados 1504/1528
Procesados 1528/1528
Clasificación NLP completa y guardada
Categoria
Movilidad y tránsito                      431
Construcción y reparaciones edilicias     304
Educación y escuelas                      255
Organizaciones sociales y comunitarias    245
Deporte y clubes deportivos               123
Plazas y espacios públicos                 55
Salud y medicina                           38
Seguridad y bomberos                       34
Medio ambiente y reciclaje                 27
Cultura y patrimonio histórico             16
Name: count, dtype: int64

In [13]:
print(dataset_tif['Categoria'].value_counts())

Categoria
Movilidad y tránsito                      431
Construcción y reparaciones edilicias     304
Educación y escuelas                      255
Organizaciones sociales y comunitarias    245
Deporte y clubes deportivos               123
Plazas y espacios públicos                 55
Salud y medicina                           38
Seguridad y bomberos                       34
Medio ambiente y reciclaje                 27
Cultura y patrimonio histórico             16
Name: count, dtype: int64