In [7]:
import pandas as pd

archivos_excel = [
    'Resultados de la votación 2017.xlsx',
    'Resultados de la votación 2018.xlsx',
    'Resultados de la votación 2019.xlsx',
    'Resultados de la votación 2021.xlsx',
    'Resultados de la votación 2022.xlsx',
    'Resultados de la votación 2023.xlsx',
    'Resultados de la votación 2024.xlsx',
    'Resultados de la votación 2025.xls'
]

for nombre in archivos_excel:
    temp_df = pd.read_excel(nombre)
    print(f"--- Columnas en {nombre} ---")
    print(temp_df.columns.tolist())
    print("\n")

--- Columnas en Resultados de la votación 2017.xlsx ---
['Cantidad de votos', 'Orden en la votación', 'GANADOR', 'BARRIO', 'PROYECTO', 'PRESUPUESTO ESTIMADO', 'Suma presupuesto proyectos ganadores']


--- Columnas en Resultados de la votación 2018.xlsx ---
['Unnamed: 0', 'Olivos - 5 proyectos ganadores', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']


--- Columnas en Resultados de la votación 2019.xlsx ---
['Nº DE PROYECTO EN LA BOLETA DEL BARRIO', 'Cantidad de votos obtenidos por el proyecto', 'Orden en la votación seguún cantidad de votos obtenidos', 'GANADOR', 'BARRIO', 'PROYECTO', 'PRESUPUESTO ESTIMADO', 'Observaciones', 'Suma presupuestos proyectos ganadores por barrio']


--- Columnas en Resultados de la votación 2021.xlsx ---
['Nro. Proyecto en el Barrio', 'Cantidad de votos obtenidos', 'Orden en la votación según cantidad de votos', 'GANADOR', 'Barrio', 'Proyecto', 'Descripción', 'Presupuesto Estimado', 'Observaciones', 'Suma presupuestos proyectos ganadores por barrio']

c:\Users\cerru\OneDrive\Documentos\TP FINAL DATOS\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

--- Columnas en Resultados de la votación 2022.xlsx ---
['N° Proyecto en el Barrio', 'Cantidad de votos obtenidos', 'Orden en la votación según cantidad de votos', 'GANADOR', 'Barrio', 'Proyecto', 'Descripción', 'Presupuesto Estimado', 'Observaciones', 'Suma presupuestos proyectos ganadores por barrio', 'Disponible para el barrio en 2023']


--- Columnas en Resultados de la votación 2023.xlsx ---
['N° Proy en el Barrio', 'Cantidad de votos obtenidos', 'Orden en la votación', 'GANADOR', 'Num barrio', 'Barrio', 'Proyecto', 'Descripción', 'Presupuesto Estimado', 'Observaciones', 'Disponible para el barrio en 2024']


--- Columnas en Resultados de la votación 2024.xlsx ---
['N° Proy en el Barrio', 'Cantidad de votos obtenidos', 'Orden en la votación', 'GANADOR', 'Num barrio', 'Barrio', 'Proyecto', 'Descripción', 'Presupuesto Estimado', 'Observaciones', 'Disponible para el barrio en 2025']


--- Columnas en Resultados de la votación 2025.xls ---
['N° Proy en el Barrio', 'Cantidad de votos obtenidos', 'Orden en la votación', 'Ganador', 'Barrio', 'Proyecto', 'Descripción', 'Presupuesto Estimado', 'Observaciones', 'Disponible para el barrio en 2026']

c:\Users\cerru\OneDrive\Documentos\TP FINAL DATOS\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [10]:
import pandas as pd

archivo_2018 = 'Resultados de la votación 2018.xlsx'

hojas_dict = pd.read_excel(archivo_2018, sheet_name=None, header=1)

lista_de_tablas = []

for nombre_de_la_hoja, tabla_de_la_hoja in hojas_dict.items():
   
    tabla_de_la_hoja.columns = [str(c).lower().strip() for c in tabla_de_la_hoja.columns]
    
    tabla_de_la_hoja['barrio'] = nombre_de_la_hoja
    
    lista_de_tablas.append(tabla_de_la_hoja)

df_2018_completo = pd.concat(lista_de_tablas, ignore_index=True)

print("Barrios procesados de las hojas:")
print(df_2018_completo['barrio'].unique())

df_2018_completo.head()

Barrios procesados de las hojas:
<StringArray>
[        'Olivos', 'Villa Martelli',  'Florida Oeste',          'Munro',
     'Carapachay',  'Villa Adelina',      'La Lucila',   'Florida Este',
  'Vicente López']
Length: 9, dtype: str

,número de proyecto,descripción,votos válidos,presupuesto estimado del proyecto,observaciones,barrio,votos
0,NaN,NaN,NaN,NaN,PP del barrio: $ 9.833.333,Olivos,NaN
1,9.0,ASOCIACIÓN VECINAL DE FOMENTO Y CULTURA NORTE ...,2753.0,7000000.0,GANADOR,Olivos,NaN
2,27.0,ESCUELAS PRIMARIA Y SECUNDARIA Nº 1: equipamiento,1590.0,2000000.0,GANADOR,Olivos,NaN
3,5.0,ESCUELA PRIMARIA Nº 2: reparaciones varias en ...,1498.0,2000000.0,excede pres. Esc. Provinciales,Olivos,NaN
4,10.0,COLEGIO VIRGEN DEL CARMEN:Cambiar cielorrasos ...,1323.0,438800.0,GANADOR,Olivos,NaN

In [12]:
import pandas as pd

dict_hojas = pd.read_excel('Resultados de la votación 2018.xlsx', sheet_name=None, header=1)

lista_final_2018 = []

for nombre_barrio, df_hoja in dict_hojas.items():
    df_hoja.columns = [str(c).lower().strip() for c in df_hoja.columns]
    
    mapeo = {
        'votos válidos': 'votos',
        'descripción': 'proyecto',
        'presupuesto estimado del proyecto': 'presupuesto',
        'observaciones': 'ganador'
    }
    
    df_hoja = df_hoja.rename(columns=mapeo)
    
    df_hoja['barrio'] = nombre_barrio
    df_hoja['año'] = 2018
    
    cols_interes = ['votos', 'barrio', 'proyecto', 'presupuesto', 'ganador', 'año']
    df_hoja = df_hoja[[c for c in cols_interes if c in df_hoja.columns]]
    
    lista_final_2018.append(df_hoja)

df_2018_final = pd.concat(lista_final_2018, ignore_index=True)

df_2018_final = df_2018_final.dropna(subset=['votos', 'proyecto'], how='all')

print("✅ ¡Listo! Ahora todos los barrios están unificados.")
df_2018_final.sample(10)

✅ ¡Listo! Ahora todos los barrios están unificados.

,votos,barrio,proyecto,presupuesto,ganador,año
34,141.0,Olivos,Centro de Investigación Histórica Vicente Lópe...,453120.0,excede presupuesto,2018
162,2028.0,Florida Este,Club Social y Deportivo Caseros: puesta en val...,3000000.0,PROYECTO GANADOR,2018
28,249.0,Olivos,Ctro. de Veteranos de Malvinas: reformas en el...,485300.0,excede presupuesto,2018
116,128.0,Munro,Centro Cultural Munro: reemplazo de marquesina,1197000.0,excede presupuesto,2018
206,116.0,Vicente López,PASEO DE LA COSTA: ejercitadores y barras de c...,1780000.0,excede presupuesto,2018
36,75.0,Olivos,Señalizar estacionamiento para discapacitados,500500.0,excede presupuesto,2018
65,569.0,Florida Oeste,Escuela Primaria Manuel Dorrego: Construcción ...,3450000.0,excede presupuesto,2018
35,117.0,Olivos,Biblioteca Popular Arandú: colocación de piso ...,197500.0,excede presupuesto,2018
87,797.0,Munro,CÁMARAS DE VIGILANCIA URBANA (varias ubicaciones),2329000.0,GANADOR,2018
10,653.0,Olivos,HOSPICE SAN CAMILO: pintura exterior,434000.0,excede presupuesto,2018

In [13]:
def categorizar_proyecto(texto):
    texto = str(texto).lower()
    if any(w in texto for w in ['escuela', 'jardín', 'colegio', 'secundaria', 'primaria', 'estudiantil', 'educación', 'educacion']):
        return 'Educación'
    elif any(w in texto for w in ['cámara', 'seguridad', 'patrullero', 'iluminación', 'luces', 'alarma', 'camara', 'iluminacion']):
        return 'Seguridad'
    elif any(w in texto for w in ['salud', 'hospital', 'unidad de respuesta', 'salita', 'maternal', 'ambulatoria']):
        return 'Salud'
    elif any(w in texto for w in ['plaza', 'parque', 'arbolado', 'vereda', 'bacheo', 'espacio público', 'plazoleta', 'espacio publico']):
        return 'Espacio Público'
    elif any(w in texto for w in ['deporte', 'club', 'gimnasio', 'playón', 'cancha', 'playon']):
        return 'Deporte'
    elif any(w in texto for w in ['cultura', 'teatro', 'museo', 'centro cultural', 'biblioteca']):
        return 'Cultura'
    else:
        return 'Otros/Varios'

In [15]:
archivos_otros_años = {
    2017: 'Resultados de la votación 2017.xlsx',
    2019: 'Resultados de la votación 2019.xlsx',
    2021: 'Resultados de la votación 2021.xlsx',
    2022: 'Resultados de la votación 2022.xlsx',
    2023: 'Resultados de la votación 2023.xlsx',
    2024: 'Resultados de la votación 2024.xlsx',
    2025: 'Resultados de la votación 2025.xls'
}

lista_dfs = []
for año, archivo in archivos_otros_años.items():
    engine = 'xlrd' if archivo.endswith('.xls') else 'openpyxl'
    df_temp = pd.read_excel(archivo, engine=engine)
    df_temp.columns = [str(c).lower().strip() for c in df_temp.columns]
    
    mapeo = {'cantidad de votos obtenidos': 'votos', 'cantidad de votos': 'votos', 
             'presupuesto estimado': 'presupuesto', 'ganador': 'ganador', 'barrio': 'barrio', 'proyecto': 'proyecto'}
    df_temp = df_temp.rename(columns=mapeo)
    df_temp['año'] = año
    lista_dfs.append(df_temp)

c:\Users\cerru\OneDrive\Documentos\TP FINAL DATOS\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\cerru\OneDrive\Documentos\TP FINAL DATOS\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [16]:
print(f"Años cargados en la lista: {[df['año'].unique()[0] for df in lista_dfs]}")

Años cargados en la lista: [np.int64(2017), np.int64(2019), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025)]

In [17]:
vilo_master = pd.concat(lista_dfs + [df_2018_final], ignore_index=True)

vilo_master['categoria'] = vilo_master['proyecto'].apply(categorizar_proyecto)
vilo_master['ganador_bin'] = vilo_master['ganador'].apply(lambda x: 1 if str(x).strip().upper() in ['SI', 'GANADOR'] else 0)

vilo_master.to_csv('dataset_final_vilo.csv', index=False, encoding='utf-8-sig')
print("¡Todo unificado con éxito!")

¡Todo unificado con éxito!

In [18]:
print(vilo_master.columns.tolist())

['votos', 'orden en la votación', 'ganador', 'barrio', 'proyecto', 'presupuesto', 'suma presupuesto proyectos ganadores', 'año', 'nº de proyecto en la boleta del barrio', 'cantidad de votos obtenidos por el proyecto', 'orden en la votación seguún cantidad de votos obtenidos', 'observaciones', 'suma presupuestos proyectos ganadores por barrio', 'nro. proyecto en el barrio', 'orden en la votación según cantidad de votos', 'descripción', 'n° proyecto en el barrio', 'disponible para el barrio en 2023', 'n° proy en el barrio', 'num barrio', 'disponible para el barrio en 2024', 'disponible para el barrio en 2025', 'disponible para el barrio en 2026', 'categoria', 'ganador_bin']

In [20]:
df_limpio = vilo_master.copy()

columnas_votos = ['cantidad de votos obtenidos por el proyecto', 'cantidad de votos obtenidos']
for col in columnas_votos:
    if col in df_limpio.columns:
        df_limpio['votos'] = df_limpio['votos'].fillna(df_limpio[col])

if 'descripción' in df_limpio.columns:
    df_limpio['proyecto'] = df_limpio['proyecto'].fillna(df_limpio['descripción'])

if 'observaciones' in df_limpio.columns:
    # Si en observaciones dice GANADOR y ganador_bin es 0, lo corregimos
    mask = df_limpio['observaciones'].str.contains('GANADOR', na=False, case=False)
    df_limpio.loc[mask, 'ganador_bin'] = 1

columnas_finales = [
    'año', 
    'barrio', 
    'proyecto', 
    'categoria', 
    'votos', 
    'presupuesto', 
    'ganador_bin'
]

dataset_tif = df_limpio[columnas_finales].copy()

dataset_tif = dataset_tif.dropna(subset=['proyecto', 'barrio'])
dataset_tif['votos'] = pd.to_numeric(dataset_tif['votos'], errors='coerce').fillna(0)
dataset_tif['presupuesto'] = pd.to_numeric(dataset_tif['presupuesto'], errors='coerce').fillna(0)

print("Dataset pulido")
print(f"Columnas resultantes: {dataset_tif.columns.tolist()}")
dataset_tif.head()

Dataset pulido
Columnas resultantes: ['año', 'barrio', 'proyecto', 'categoria', 'votos', 'presupuesto', 'ganador_bin']

,año,barrio,proyecto,categoria,votos,presupuesto,ganador_bin
0,2017,Villa Martelli,BOMBEROS VOLUNTARIOS DE VICENTE LÓPEZ - 25 equ...,Otros/Varios,959.0,978500.0,1
1,2017,Villa Martelli,CAMPAÑA DE CONCIENTIZACIÓN SOBRE EL BULLYING -...,Educación,506.0,193892.0,1
2,2017,Villa Martelli,FUNDACION CAMINO - Remodelación interior y fac...,Otros/Varios,487.0,1500000.0,1
3,2017,Villa Martelli,ESCUELA SECUNDARIA Nº 2 (provincial) - Reparac...,Educación,482.0,1200000.0,1
4,2017,Villa Martelli,BIBLIOTECA FROILÁN GONZÁLEZ - Compra de mobili...,Seguridad,446.0,132000.0,1

In [21]:
dataset_tif.to_csv('dataset_final_vilo.csv', index=False, encoding='utf-8-sig')

print("Archivo 'dataset_final_vilo.csv' actualizado")

Archivo 'dataset_final_vilo.csv' actualizado

In [25]:
import pandas as pd

def categorizar_proyecto_ultra(texto):
    texto = str(texto).lower()
    if any(w in texto for w in ['escuela', 'jardín', 'jardin', 'colegio', 'secundaria', 'primaria', 'estudiantil', 'educación', 'educacion', 'aula', 'biblioteca', 'pizarra', 'notebook', 'computadora']):
        return 'Educación'
    elif any(w in texto for w in ['cámara', 'camara', 'seguridad', 'patrullero', 'iluminación', 'iluminacion', 'luces', 'alarma', 'vigilancia', 'tótem', 'totem', 'monitoreo', 'botón', 'boton']):
        return 'Seguridad'
    elif any(w in texto for w in ['salud', 'hospital', 'unidad de respuesta', 'salita', 'maternal', 'ambulatoria', 'caps', 'ambulancia', 'odontológico', 'ecógrafo', 'médico']):
        return 'Salud'
    elif any(w in texto for w in ['plaza', 'parque', 'arbolado', 'vereda', 'bacheo', 'espacio público', 'espacio publico', 'plazoleta', 'asfalto', 'pavimento', 'luminaria', 'semáforo', 'semaforo', 'señalización', 'señaletica', 'poda', 'residuos', 'reciclado']):
        return 'Espacio Público'
    elif any(w in texto for w in ['deporte', 'club', 'gimnasio', 'playón', 'playon', 'cancha', 'polideportivo', 'fútbol', 'basquet', 'natatorio']):
        return 'Deporte'
    elif any(w in texto for w in ['cultura', 'teatro', 'museo', 'centro cultural', 'talleres', 'música', 'musica', 'orquesta', 'instrumentos']):
        return 'Cultura'
    else:
        return 'Otros/Varios'

dataset_tif['categoria'] = dataset_tif['proyecto'].apply(categorizar_proyecto_ultra)
dataset_tif.to_csv('dataset_final_vilo.csv', index=False, sep=';', encoding='utf-8-sig')

print("Nueva distribución tras el ajuste:")
print(dataset_tif['categoria'].value_counts())

Nueva distribución tras el ajuste:
categoria
Otros/Varios       646
Educación          434
Espacio Público    148
Deporte            147
Seguridad           54
Cultura             45
Salud                7
Name: count, dtype: int64