In [2]:
import pandas as pd
import numpy as np
import unicodedata

# Revisión de los archivos originales en la carpeta crudos
archivos_excel = [
    'DATOS/Datos crudos/Resultados de la votación 2017.xlsx',
    'DATOS/Datos crudos/Resultados de la votación 2018.xlsx',
    'DATOS/Datos crudos/Resultados de la votación 2019.xlsx',
    'DATOS/Datos crudos/Resultados de la votación 2021.xlsx',
    'DATOS/Datos crudos/Resultados de la votación 2022.xlsx',
    'DATOS/Datos crudos/Resultados de la votación 2023.xlsx',
    'DATOS/Datos crudos/Resultados de la votación 2024.xlsx',
    'DATOS/Datos crudos/Resultados de la votación 2025.xls'
]

for nombre in archivos_excel:
    temp_df = pd.read_excel(nombre)
    print(f"--- Columnas en {nombre} ---")
    print(temp_df.columns.tolist())
    print("\n")

--- Columnas en DATOS/Datos crudos/Resultados de la votación 2017.xlsx ---
['Cantidad de votos', 'Orden en la votación', 'GANADOR', 'BARRIO', 'PROYECTO', 'PRESUPUESTO ESTIMADO', 'Suma presupuesto proyectos ganadores']


--- Columnas en DATOS/Datos crudos/Resultados de la votación 2018.xlsx ---
['Unnamed: 0', 'Olivos - 5 proyectos ganadores', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']


--- Columnas en DATOS/Datos crudos/Resultados de la votación 2019.xlsx ---
['Nº DE PROYECTO EN LA BOLETA DEL BARRIO', 'Cantidad de votos obtenidos por el proyecto', 'Orden en la votación seguún cantidad de votos obtenidos', 'GANADOR', 'BARRIO', 'PROYECTO', 'PRESUPUESTO ESTIMADO', 'Observaciones', 'Suma presupuestos proyectos ganadores por barrio']


--- Columnas en DATOS/Datos crudos/Resultados de la votación 2021.xlsx ---
['Nro. Proyecto en el Barrio', 'Cantidad de votos obtenidos', 'Orden en la votación según cantidad de votos', 'GANADOR', 'Barrio', 'Proyecto', 'Descripción', 'Presupuesto Estimado', 'Observaciones', 'Suma presupuestos proyectos ganadores por barrio']

c:\Users\cerru\OneDrive\Documentos\TP FINAL DATOS\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

--- Columnas en DATOS/Datos crudos/Resultados de la votación 2022.xlsx ---
['N° Proyecto en el Barrio', 'Cantidad de votos obtenidos', 'Orden en la votación según cantidad de votos', 'GANADOR', 'Barrio', 'Proyecto', 'Descripción', 'Presupuesto Estimado', 'Observaciones', 'Suma presupuestos proyectos ganadores por barrio', 'Disponible para el barrio en 2023']


--- Columnas en DATOS/Datos crudos/Resultados de la votación 2023.xlsx ---
['N° Proy en el Barrio', 'Cantidad de votos obtenidos', 'Orden en la votación', 'GANADOR', 'Num barrio', 'Barrio', 'Proyecto', 'Descripción', 'Presupuesto Estimado', 'Observaciones', 'Disponible para el barrio en 2024']


--- Columnas en DATOS/Datos crudos/Resultados de la votación 2024.xlsx ---
['N° Proy en el Barrio', 'Cantidad de votos obtenidos', 'Orden en la votación', 'GANADOR', 'Num barrio', 'Barrio', 'Proyecto', 'Descripción', 'Presupuesto Estimado', 'Observaciones', 'Disponible para el barrio en 2025']


--- Columnas en DATOS/Datos crudos/Resultados de la votación 2025.xls ---
['N° Proy en el Barrio', 'Cantidad de votos obtenidos', 'Orden en la votación', 'Ganador', 'Barrio', 'Proyecto', 'Descripción', 'Presupuesto Estimado', 'Observaciones', 'Disponible para el barrio en 2026']

c:\Users\cerru\OneDrive\Documentos\TP FINAL DATOS\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [3]:
#El archivo de 2018 tenía los datos separados por hoja por barrio. Se recorre cada hoja, se le asigna el nombre del barrio a cada fila y luego las une en una sola tabla para analizar el año completo

archivo_2018 = 'DATOS/Datos crudos/Resultados de la votación 2018.xlsx'

hojas_dict = pd.read_excel(archivo_2018, sheet_name=None, header=1)

lista_de_tablas = []

for nombre_de_la_hoja, tabla_de_la_hoja in hojas_dict.items():
    tabla_de_la_hoja.columns = [str(c).lower().strip() for c in tabla_de_la_hoja.columns]
    
    tabla_de_la_hoja['Localidades'] = nombre_de_la_hoja
    
    lista_de_tablas.append(tabla_de_la_hoja)

df_2018_completo = pd.concat(lista_de_tablas, ignore_index=True)

print("Barrios procesados de las hojas:")
print(df_2018_completo['Localidades'].unique())

df_2018_completo.head()

Barrios procesados de las hojas:
<StringArray>
[        'Olivos', 'Villa Martelli',  'Florida Oeste',          'Munro',
     'Carapachay',  'Villa Adelina',      'La Lucila',   'Florida Este',
  'Vicente López']
Length: 9, dtype: str

,número de proyecto,descripción,votos válidos,presupuesto estimado del proyecto,observaciones,Localidades,votos
0,NaN,NaN,NaN,NaN,PP del barrio: $ 9.833.333,Olivos,NaN
1,9.0,ASOCIACIÓN VECINAL DE FOMENTO Y CULTURA NORTE ...,2753.0,7000000.0,GANADOR,Olivos,NaN
2,27.0,ESCUELAS PRIMARIA Y SECUNDARIA Nº 1: equipamiento,1590.0,2000000.0,GANADOR,Olivos,NaN
3,5.0,ESCUELA PRIMARIA Nº 2: reparaciones varias en ...,1498.0,2000000.0,excede pres. Esc. Provinciales,Olivos,NaN
4,10.0,COLEGIO VIRGEN DEL CARMEN:Cambiar cielorrasos ...,1323.0,438800.0,GANADOR,Olivos,NaN

In [4]:
#Se mapea y limpian los datos de 2018, renombrando columnas originales a nombres comunes con los otros años. 
#Además filtra la info relevante y elimina las filas vacías
dict_hojas = pd.read_excel('DATOS/Datos crudos/Resultados de la votación 2018.xlsx', sheet_name=None, header=1)

lista_final_2018 = []

for nombre_barrio, df_hoja in dict_hojas.items():
    df_hoja.columns = [str(c).lower().strip() for c in df_hoja.columns]
    
    mapeo = {
        'votos válidos': 'Votos',
        'descripción': 'Proyecto',
        'presupuesto estimado del proyecto': 'Presupuesto',
        'observaciones': 'Ganador'
    }
    
    df_hoja = df_hoja.rename(columns=mapeo)
    
    df_hoja['Barrio'] = nombre_barrio
    df_hoja['Año'] = 2018
    
    cols_interes = ['Votos', 'Localidades', 'Proyecto', 'Presupuesto', 'Ganador', 'Año']
    df_hoja = df_hoja[[c for c in cols_interes if c in df_hoja.columns]]
    
    lista_final_2018.append(df_hoja)

df_2018_final = pd.concat(lista_final_2018, ignore_index=True)

df_2018_final = df_2018_final.dropna(subset=['Votos', 'Proyecto'], how='all')

print("Todas las localidades están unificadas.")
df_2018_final.sample(10)

Todas las localidades están unificadas.

,Votos,Proyecto,Presupuesto,Ganador,Año
144,124.0,PUNTO DE RECICLADO AUTOMÁTICOS,348950.0,excede presupuesto,2018
52,216.0,Homenaje a Hugo Pane: instalación de placa con...,80000.0,GANADOR,2018
7,898.0,Cámaras de Seguridad: J.B Alberdi y Blas Parer...,4675000.0,excede presupuesto,2018
135,54.0,H2O al rescate: TALLERES EN ESCUELAS SOBRE EL ...,180000.0,NaN,2018
169,NaN,ESCUELA PRIMARIA Nº 9: reparación de paredes y...,2000000.0,excede presupuesto,2018
167,NaN,ESCUELA PRIMARIA Nº 3: mejoras en el gimnasio ...,2000000.0,excede presupuesto,2018
177,NaN,RAMPAS EN EL BARRIO Y SENDAS PEATONALES EN LA ...,590000.0,excede presupuesto,2018
206,NaN,PASEO DE LA COSTA: ejercitadores y barras de c...,1780000.0,excede presupuesto,2018
198,NaN,RAMPAS EN ESQUINAS (varias ubicaciones),760000.0,excede presupuesto,2018
74,227.0,"Centro Barrial Infantil ""Las Flores"": equipami...",488684.0,excede presupuesto,2018

In [5]:
#Se procesan los años estandarizando los nombres de las columnas y chequear que todos los archivos se carguen sin errores de compatibilidad
archivos_otros_años = {
    2017: 'DATOS/Datos crudos/Resultados de la votación 2017.xlsx',
    2019: 'DATOS/Datos crudos/Resultados de la votación 2019.xlsx',
    2021: 'DATOS/Datos crudos/Resultados de la votación 2021.xlsx',
    2022: 'DATOS/Datos crudos/Resultados de la votación 2022.xlsx',
    2023: 'DATOS/Datos crudos/Resultados de la votación 2023.xlsx',
    2024: 'DATOS/Datos crudos/Resultados de la votación 2024.xlsx',
    2025: 'DATOS/Datos crudos/Resultados de la votación 2025.xls'
}

lista_dfs = []
for año, archivo in archivos_otros_años.items():
    engine = 'xlrd' if archivo.endswith('.xls') else 'openpyxl'
    
    df_temp = pd.read_excel(archivo, engine=engine)
    
    df_temp.columns = [str(c).lower().strip() for c in df_temp.columns]
    
    mapeo = {
        'cantidad de votos obtenidos': 'Votos', 
        'cantidad de votos': 'Votos', 
        'presupuesto estimado': 'Presupuesto', 
        'ganador': 'Ganador', 
        'barrio': 'Localidades', 
        'proyecto': 'Proyecto'
    }
    
    df_temp = df_temp.rename(columns=mapeo)
    df_temp['Año'] = año
    lista_dfs.append(df_temp)

c:\Users\cerru\OneDrive\Documentos\TP FINAL DATOS\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\cerru\OneDrive\Documentos\TP FINAL DATOS\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [6]:
#Carga del archivo histórico de proyectos ganadores
archivo_historico= 'DATOS/Datos crudos/Históricos Presupuesto.xlsx'

df_historico=pd.read_excel(archivo_historico)

#Se filtran sólo los años entre 2013 y 2016
df_historico=df_historico[df_historico['Año'].isin([2013,2014,2015,2016])].copy()

#Renombramos columnas
mapeo_historico={
    'Año':'Año',
    'Barrio':'Localidades',
    'Título Proyecto':'Proyecto',
    'Presupuesto invertido':'Presupuesto',
    'Cantidad de votos válidos obtenidos':'Votos'
}

df_historico=df_historico.rename(columns=mapeo_historico)

cols_a_limpiar = ['Votos', 'Presupuesto']

for col in cols_a_limpiar:
    #Convertimos a string y quitamos puntos, comas, signos de pesos y espacios
    df_historico[col] = df_historico[col].astype(str).str.replace(r'[$.]', '', regex=True).str.replace(',', '.', regex=True).str.strip()
   
    #Convertimos a numérico y luego a entero
    df_historico[col] = pd.to_numeric(df_historico[col], errors='coerce').fillna(0).astype(int)

#Se aplica la función de categorías como "Sin Clasificar" para luego sobreescribirlo 
df_historico['Categoria'] = 'Sin clasificar'

filtro_cero = (df_historico['Votos'] == 0)

# Imputamos la media de 540
df_historico.loc[filtro_cero, 'Votos'] = 540

# Nos aseguramos que el ganador sea 1
df_historico['Ganador_bin'] = 1

# Forzamos a que sea un número entero
df_historico['Ganador_bin'] = df_historico['Ganador_bin'].astype(int)

# Seleccionamos las columnas finales
columnas_finales = ['Año','Localidades','Proyecto','Categoria','Votos','Presupuesto','Ganador_bin']
df_historico_final = df_historico[columnas_finales]

# Agregamos a nuestra lista
lista_dfs.append(df_historico_final)

print("2013-2016 integrados")

2013-2016 integrados

In [ ]:
# Se unifica la lista
vilo_master = pd.concat(lista_dfs + [df_2018_final], ignore_index=True)

# Colocamos la categoría como "Sin clasificar" para luego sobreescribirlo 
vilo_master['Categoria'] = 'Sin clasificar'

# Creamos la lógica para los años que SÍ tienen la columna 'Ganador'
condicion_ganador = vilo_master['Ganador'].apply(lambda x: str(x).strip().upper() in ['SI', 'GANADOR'])

# Solo aplicamos la lógica a las filas que NO son 2013-2016
mascara_otros_años = ~vilo_master['Año'].isin([2013, 2014, 2015, 2016])

vilo_master.loc[condicion_ganador & mascara_otros_años, 'Ganador_bin'] = 1
vilo_master.loc[~condicion_ganador & mascara_otros_años, 'Ganador_bin'] = 0

# Finalmente, para asegurarnos de que no quede ningún NaN, rellenamos cualquier hueco que haya quedado con 0
vilo_master['Ganador_bin'] = vilo_master['Ganador_bin'].fillna(0).astype(int)

#Guardamos el resultado final
vilo_master.to_csv('DATOS/Datos procesados/dataset_final_vilo.csv', index=False, encoding='utf-8-sig')
print("¡Todo unificado con éxito!")

¡Todo unificado con éxito!

In [8]:
#Hacemos la copia
df_limpio = vilo_master.copy()

#Unificamos columnas de votos
columnas_votos = ['cantidad de votos obtenidos por el proyecto', 'cantidad de votos obtenidos']
for col in columnas_votos:
    if col in df_limpio.columns:
        df_limpio['Votos'] = df_limpio['Votos'].fillna(df_limpio[col])

#Unificamos descripción
if 'descripción' in df_limpio.columns:
    df_limpio['proyecto'] = df_limpio['Proyecto'].fillna(df_limpio['descripción'])

#Rescatamos ganadores de observaciones
if 'observaciones' in df_limpio.columns:
    mask = df_limpio['observaciones'].str.contains('GANADOR', na=False, case=False)
    df_limpio.loc[mask, 'Ganador_bin'] = 1

# Limpiamos espacios y mayúsculas
df_limpio['Localidades'] = df_limpio['Localidades'].astype(str).str.upper().str.strip()

# Diccionario de corrección
mapeo_localidades = {
    'V. LOPEZ': 'Vicente López',
    'VTE LOPEZ': 'Vicente López',
    'VICENTE LOPEZ': 'Vicente López',
    'VICENTE LÓPEZ': 'Vicente López',
    'FLORIDA ESTE': 'Florida Este',
    'FLORIDA OESTE': 'Florida Oeste',
    'LA LUCILA': 'La Lucila',
    'MUNRO': 'Munro',
    'OLIVOS': 'Olivos',
    'CARAPACHAY': 'Carapachay',
    'VILLA ADELINA': 'Villa Adelina',
    'VILLA MARTELLI': 'Villa Martelli'
}

# Aplicamos el mapeo, si no está en el diccionario, mantiene el original
df_limpio['Localidades'] = df_limpio['Localidades'].map(mapeo_localidades).fillna(df_limpio['Localidades'])

#Selección de columnas finales
columnas_finales = [
    'Año', 
    'Localidades', 
    'Proyecto', 
    'Categoria', 
    'Votos', 
    'Presupuesto', 
    'Ganador_bin'
]

dataset_tif = df_limpio[columnas_finales].copy()

#Limpieza de filas y conversión a ENTEROS (int)
dataset_tif = dataset_tif.dropna(subset=['Proyecto', 'Localidades'])

dataset_tif['Votos'] = pd.to_numeric(dataset_tif['Votos'], errors='coerce').fillna(0).astype(int)
dataset_tif['Presupuesto'] = pd.to_numeric(dataset_tif['Presupuesto'], errors='coerce').fillna(0).astype(int)

# CORRECCIÓN DE RUTAS:
ruta_salida = 'DATOS/Datos procesados/dataset_final_vilo.csv'

dataset_tif.to_csv(ruta_salida, index=False, sep=';', encoding='utf-8-sig')

print("Dataset pulido y guardado")
print(f"Total de registros: {len(dataset_tif)}")
dataset_tif.head()

Dataset pulido y guardado
Total de registros: 1528

,Año,Localidades,Proyecto,Categoria,Votos,Presupuesto,Ganador_bin
0,2017,Villa Martelli,BOMBEROS VOLUNTARIOS DE VICENTE LÓPEZ - 25 equ...,Sin clasificar,959,978500,1
1,2017,Villa Martelli,CAMPAÑA DE CONCIENTIZACIÓN SOBRE EL BULLYING -...,Sin clasificar,506,193892,1
2,2017,Villa Martelli,FUNDACION CAMINO - Remodelación interior y fac...,Sin clasificar,487,1500000,1
3,2017,Villa Martelli,ESCUELA SECUNDARIA Nº 2 (provincial) - Reparac...,Sin clasificar,482,1200000,1
4,2017,Villa Martelli,BIBLIOTECA FROILÁN GONZÁLEZ - Compra de mobili...,Sin clasificar,446,132000,1

In [9]:
import os
import time
from groq import Groq
from dotenv import load_dotenv

load_dotenv()
client = Groq(api_key=os.getenv("GROQ_API_KEY"))

categorias = [
    'Salud y medicina',
    'Cultura y patrimonio histórico',
    'Educación y escuelas',
    'Seguridad y bomberos',
    'Movilidad y tránsito',
    'Medio ambiente y reciclaje',
    'Deporte y clubes deportivos',
    'Plazas y espacios públicos',
    'Construcción y reparaciones edilicias',
    'Organizaciones sociales y comunitarias'
]

def clasificar_con_groq(titulo):
    prompt = f"""Clasificá este proyecto de presupuesto participativo en UNA SOLA de estas categorías:
{chr(10).join(f'- {c}' for c in categorias)}

Proyecto: {titulo}

Respondé ÚNICAMENTE con el nombre exacto de la categoría, sin explicaciones ni puntos."""

    respuesta = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[{"role": "user", "content": prompt}],
        temperature=0
    )
    
    return respuesta.choices[0].message.content.strip()

categorias_resultado = []

for i, titulo in enumerate(dataset_tif['Proyecto'].tolist()):
    try:
        categoria = clasificar_con_groq(titulo)
        categorias_resultado.append(categoria)
    except Exception as e:
        print(f"Error en fila {i}: {e}")
        categorias_resultado.append("Sin clasificar")
    
    if (i + 1) % 50 == 0:
        print(f"Procesados {i+1}/1528")
    
    time.sleep(2)

dataset_tif['Categoria'] = categorias_resultado

dataset_tif.to_csv(
    'DATOS/Datos procesados/dataset_final_vilo.csv',
    index=False, sep=';', encoding='utf-8-sig'
)
print("Clasificación completa y guardada")

Procesados 50/1528
Procesados 100/1528
Procesados 150/1528
Procesados 200/1528
Procesados 250/1528
Procesados 300/1528
Procesados 350/1528
Procesados 400/1528
Procesados 450/1528
Procesados 500/1528
Procesados 550/1528
Procesados 600/1528
Procesados 650/1528
Procesados 700/1528
Procesados 750/1528
Procesados 800/1528
Procesados 850/1528
Procesados 900/1528
Procesados 950/1528
Procesados 1000/1528
Procesados 1050/1528
Procesados 1100/1528
Procesados 1150/1528
Procesados 1200/1528
Procesados 1250/1528
Procesados 1300/1528
Procesados 1350/1528
Procesados 1400/1528
Procesados 1450/1528
Procesados 1500/1528
Clasificación completa y guardada

In [10]:
print(dataset_tif['Categoria'].value_counts())

Categoria
Educación y escuelas                      344
Organizaciones sociales y comunitarias    250
Movilidad y tránsito                      171
Construcción y reparaciones edilicias     169
Medio ambiente y reciclaje                137
Plazas y espacios públicos                127
Deporte y clubes deportivos               120
Seguridad y bomberos                      105
Cultura y patrimonio histórico             78
Salud y medicina                           27
Name: count, dtype: int64